export const skillIcons1 = [
  { src: "/Skills/NextJS-Dark.svg", title: "Next.js" },
  { src: "/Skills/NodeJS-Dark.svg", title: "Node.js" },
  { src: "/Skills/Postman.svg", title: "Postman" },
  { src: "/Skills/Python-Dark.svg", title: "Python" },
  { src: "/Skills/React-Dark.svg", title: "React" },
  { src: "/Skills/Redux.svg", title: "Redux" },
  { src: "/Skills/Regex-Dark.svg", title: "Regex" },
  { src: "/Skills/ScikitLearn-Dark.svg", title: "Scikit-learn" },
  { src: "/Skills/TailwindCSS-Dark.svg", title: "Tailwind CSS" },
  { src: "/Skills/Tensorflow-Dark.svg", title: "TensorFlow" },
  { src: "/Skills/TypeScript.svg", title: "TypeScript" },
];
export const skillIcons2 = [
  { src: "/Skills/Arduino.svg", title: "Arduino" },
  { src: "/Skills/Bootstrap.svg", title: "Bootstrap" },
  { src: "/Skills/JavaScript.svg", title: "JavaScript" },
  { src: "/Skills/CPP.svg", title: "C++" },
  { src: "/Skills/CSS.svg", title: "CSS" },
  { src: "/Skills/Figma-Dark.svg", title: "Figma" },
  { src: "/Skills/Git.svg", title: "Git" },
  { src: "/Skills/Java-Dark.svg", title: "Java" },
  { src: "/Skills/Laravel-Dark.svg", title: "Laravel" },
  { src: "/Skills/LaTeX-Dark.svg", title: "LaTeX" },
  { src: "/Skills/MySQL-Dark.svg", title: "MySQL" },
];
